# Generated by Django 6.0.1 on 2026-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0002_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_manage_users', 'Pode gerenciar usuários'), ('can_view_reports', 'Pode visualizar relatórios'), ('can_manage_system', 'Pode gerenciar sistema'), ('can_manage_backups', 'Pode gerenciar backups')]},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='accept_terms',
            new_name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='papel',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='terms_accepted_at',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Aprovado pelo administrador'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('produtor', 'Produtor (Dono da Fazenda)'), ('veterinario', 'Veterinário'), ('funcionario', 'Funcionário da Fazenda'), ('gestor_financeiro', 'Gestor Financeiro')], default='funcionario', help_text='Tipo de usuário na plataforma', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fazenda_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
