# Generated by Django 6.0.1 on 2026-03-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0004_customuser_email_confirmation_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='area_atuacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
