# Generated by Django 6.0.1 on 2026-03-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0005_perfil_area_atuacao_perfil_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='needs_password_setup',
            field=models.BooleanField(default=False),
        ),
    ]
