# Generated by Django 6.0.1 on 2026-05-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0008_customuser_is_blocked_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_blocked',
        ),
    ]
