# Generated by Django 6.0.1 on 2026-05-14 23:47

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0009_remove_customuser_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Atividade de Usuário', 'verbose_name_plural': 'Atividades de Usuários'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Usuário bloqueado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='area_atuacao',
            field=models.CharField(blank=True, help_text='Área de atuação (para Gestores Financeiros)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento (não pode ser futura)', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço completo', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='especialidade',
            field=models.CharField(blank=True, help_text='Especialidade médica (para Veterinários)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fazenda_nome',
            field=models.CharField(blank=True, help_text='Nome da fazenda (para Produtores)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do usuário', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='setor',
            field=models.CharField(blank=True, help_text='Setor de trabalho (para Funcionários)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone no formato internacional (ex: +244912345678)', max_length=128, null=True, region='AO'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registro'), ('password_change', 'Mudança de Senha'), ('profile_update', 'Atualização de Perfil'), ('admin_action', 'Ação Administrativa'), ('user_approve', 'Aprovação de Usuário'), ('user_block', 'Bloqueio de Usuário'), ('user_delete', 'Exclusão de Usuário'), ('role_change', 'Mudança de Função'), ('settings_change', 'Alteração de Configurações')], max_length=30),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
