# Generated by Django 5.2.6 on 2026-05-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0009_remove_customuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Indica se o usuário está bloqueado pelo sistema'),
        ),
    ]
