# Generated by Django 6.0.1 on 2026-05-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0010_alter_perfil_options_alter_useractivity_options_and_more'),
        ('login_cadastro', '0010_customuser_is_blocked'),
    ]

    operations = [
    ]
