# Generated by Django 5.2.6 on 2026-05-25 11:22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0011_merge_20260520_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Indica se o usuário está bloqueado pelo sistema'),
        ),
    ]
