# Generated by Django 6.0.1 on 2026-05-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0011_merge_20260519_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Indica se o usuário está bloqueado pelo sistema'),
        ),
    ]
