# Generated by Django 6.0.1 on 2026-06-07 16:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0012_alter_customuser_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone no formato internacional (ex: +244912345678)', max_length=20, null=True, region='AO'),
        ),
    ]
