# Generated by Django 6.0.1 on 2026-06-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0013_alter_perfil_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone no formato internacional (ex: +244912345678)', max_length=20, null=True),
        ),
    ]
