# Generated by Django 6.0.1 on 2026-07-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0011_merge_20260519_2102'),
        ('login_cadastro', '0014_telefone_charfield'),
    ]

    operations = [
    ]
