# Generated by Django 6.0.1 on 2026-06-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario_dashboard', '0002_alter_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='urgencia',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='baixa', max_length=10),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.CharField(choices=[('doenca', 'Doença'), ('acidente', 'Acidente'), ('fuga', 'Fuga'), ('estrutura', 'Estrutura danificada'), ('falta_insumos', 'Falta de Insumos'), ('nascimento', 'Nascimento'), ('morte', 'Morte'), ('outro', 'Outro')], max_length=20),
        ),
    ]
