# Generated by Django 6.0.1 on 2026-05-13 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtor_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSaude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('doenca', 'Doença'), ('vacina', 'Vacina Atrasada'), ('tratamento', 'Tratamento Pendente'), ('observacao', 'Observação'), ('surto', 'Surto')], max_length=20)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='produtor_dashboard.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_saude', to='produtor_dashboard.fazenda')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinario_alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('rotina', 'Consulta de Rotina'), ('emergencia', 'Emergência'), ('retorno', 'Retorno'), ('vacina', 'Vacinação'), ('cirurgia', 'Cirurgia'), ('exame', 'Exame')], max_length=20)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('adiado', 'Adiado')], default='agendado', max_length=20)),
                ('data_consulta', models.DateField()),
                ('horario', models.TimeField()),
                ('descricao', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('prescricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='produtor_dashboard.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='produtor_dashboard.fazenda')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinario_consultas',
                'ordering': ['data_consulta', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='LembreteSaude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_lembrete', models.DateField()),
                ('frequencia', models.CharField(choices=[('unico', 'Único'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='unico', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='produtor_dashboard.fazenda')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinario_lembretes',
                'ordering': ['data_lembrete'],
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnostico', models.TextField()),
                ('tratamento', models.TextField()),
                ('medicamentos', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('interrompido', 'Interrompido')], default='em_andamento', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='produtor_dashboard.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='produtor_dashboard.fazenda')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinario_tratamentos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_vacina', models.CharField(max_length=200)),
                ('lote', models.CharField(max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('data_proxima_dose', models.DateField(blank=True, null=True)),
                ('dose', models.CharField(max_length=50)),
                ('via_aplicacao', models.CharField(choices=[('intramuscular', 'Intramuscular'), ('subcutanea', 'Subcutânea'), ('oral', 'Oral'), ('intravenosa', 'Intravenosa')], max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='produtor_dashboard.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='produtor_dashboard.fazenda')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinario_vacinas',
                'ordering': ['-data_aplicacao'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('bovinos', 'Bovinos'), ('suinos', 'Suínos'), ('caprinos', 'Caprinos'), ('ovinos', 'Ovinos'), ('equinos', 'Equinos'), ('geral', 'Clínica Geral')], default='geral', max_length=50)),
                ('registro_crmv', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarios', to='produtor_dashboard.fazenda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veterinario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veterinário',
                'verbose_name_plural': 'Veterinários',
                'db_table': 'veterinario',
            },
        ),
    ]
