# Generated by Django 6.0.1 on 2026-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinario_dashboard', '0001_allow_crmv_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='especialidade',
            field=models.CharField(choices=[('bovinos', 'Bovinos'), ('geral', 'Clínica Geral')], default='geral', max_length=50),
        ),
    ]
