# Generated by Django 6.0.1 on 2026-05-12 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtor_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_financeiras', to='produtor_dashboard.fazenda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade Financeira',
                'verbose_name_plural': 'Atividades Financeiras',
                'db_table': 'gestor_atividades',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('racao', 'Ração'), ('veterinario', 'Veterinário'), ('medicamentos', 'Medicamentos'), ('equipamentos', 'Equipamentos'), ('manutencao', 'Manutenção'), ('funcionarios', 'Funcionários'), ('energia', 'Energia'), ('agua', 'Água'), ('transporte', 'Transporte'), ('impostos', 'Impostos'), ('outros', 'Outros')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/despesas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='produtor_dashboard.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='produtor_dashboard.fazenda')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'db_table': 'gestor_despesas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='GestorFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='Financeiro', max_length=100)),
                ('nivel_acesso', models.CharField(choices=[('basico', 'Básico'), ('avancado', 'Avançado'), ('total', 'Total')], default='avancado', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores_financeiros', to='produtor_dashboard.fazenda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_financeiro_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestor Financeiro',
                'verbose_name_plural': 'Gestores Financeiros',
                'db_table': 'gestor_financeiro',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('venda_animal', 'Venda de Animal'), ('venda_produto', 'Venda de Produto'), ('venda_leite', 'Venda de Leite'), ('subsidio', 'Subsídio/Governo'), ('emprestimo', 'Empréstimo'), ('outros', 'Outros')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/receitas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='produtor_dashboard.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='produtor_dashboard.fazenda')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'gestor_receitas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('total_receitas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lucro_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dados_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_financeiros', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Relatório Financeiro',
                'verbose_name_plural': 'Relatórios Financeiros',
                'db_table': 'gestor_relatorios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('lucro', 'Lucro')], max_length=20)),
                ('periodo', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ano', models.IntegerField(default=2026)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_financeiras', to='produtor_dashboard.fazenda')),
            ],
            options={
                'db_table': 'gestor_metas',
                'unique_together': {('fazenda', 'tipo', 'periodo', 'ano', 'mes')},
            },
        ),
    ]
