# Generated by Django 6.0.1 on 2026-06-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_financeiro_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='comprador',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='receita',
            name='forma_pagamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='receita',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
