# Generated by Django 6.0.1 on 2026-05-17 14:44

import components.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('racao', 'Ração'), ('medicamento', 'Medicamento'), ('vacina', 'Vacina'), ('ferramenta', 'Ferramenta'), ('equipamento', 'Equipamento'), ('outro', 'Outro')], max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade'), ('cx', 'Caixa')], max_length=20)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.CharField(max_length=20, unique=True, validators=[components.validators.validate_brinco])),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('raca', models.CharField(choices=[('nelore', 'Nelore'), ('angus', 'Angus'), ('holandes', 'Holandês'), ('girolando', 'Girolando'), ('sindi', 'Sindi'), ('brahman', 'Brahman'), ('guzerat', 'Guzerá'), ('outro', 'Outro')], max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('peso_nascimento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vendido', 'Vendido'), ('abatido', 'Abatido'), ('morto', 'Morto')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_mae', to='components.animal')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_pai', to='components.animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('concentrado', 'Concentrado'), ('silagem', 'Silagem'), ('pastagem', 'Pastagem'), ('suplemento', 'Suplemento Mineral'), ('outro', 'Outro')], max_length=50)),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacao', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes', to='components.animal')),
            ],
            options={
                'verbose_name': 'Alimentação',
                'verbose_name_plural': 'Alimentações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PesoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesagens', to='components.animal')),
            ],
            options={
                'verbose_name': 'Peso do Animal',
                'verbose_name_plural': 'Pesagens',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('produtor', 'Produtor Rural'), ('veterinario', 'Médico Veterinário'), ('funcionario', 'Funcionário'), ('gestor_financeiro', 'Gestor Financeiro'), ('administrador', 'Administrador')], default='produtor', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[components.validators.validate_telefone])),
                ('fazenda', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('categoria', models.CharField(choices=[('venda_animal', 'Venda de Animal'), ('compra_animal', 'Compra de Animal'), ('compra_insumo', 'Compra de Insumo'), ('medicamento', 'Medicamento'), ('alimentacao', 'Alimentação'), ('servico', 'Serviço'), ('manutencao', 'Manutenção'), ('salario', 'Salário'), ('imposto', 'Imposto'), ('outro', 'Outro')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateField(auto_now_add=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='components.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='components.user')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('data_limite', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='components.animal')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='components.user')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-prioridade', 'data_limite'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='components.user')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('diagnostico', models.TextField()),
                ('tratamento', models.TextField(blank=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='components.animal')),
                ('veterinario', models.ForeignKey(limit_choices_to={'role': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='components.user')),
            ],
            options={
                'verbose_name': 'Consulta Veterinária',
                'verbose_name_plural': 'Consultas Veterinárias',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='components.user'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.TextField(blank=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('notificacoes_email', models.BooleanField(default=True)),
                ('notificacoes_sms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='components.user')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('data_aplicacao', models.DateField()),
                ('data_proxima', models.DateField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('observacoes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='components.animal')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'ordering': ['-data_aplicacao'],
            },
        ),
    ]
