# Generated by Django 6.0.1 on 2026-05-12 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brinco', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(choices=[('bovino', 'Bovino'), ('suino', 'Suíno'), ('caprino', 'Caprino'), ('ovino', 'Ovino'), ('equino', 'Equino'), ('avicola', 'Aves')], max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('peso_atual', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('peso_nascimento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_nascimento', models.DateField()),
                ('idade_meses', models.IntegerField(default=0)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('doente', 'Doente'), ('vendido', 'Vendido'), ('morto', 'Morto')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('vacinacao', 'Vacinação'), ('medicacao', 'Medicação'), ('consulta', 'Consulta'), ('cirurgia', 'Cirurgia'), ('exame', 'Exame')], max_length=20)),
                ('descricao', models.TextField()),
                ('medicamento', models.CharField(blank=True, max_length=200)),
                ('dose', models.CharField(blank=True, max_length=50)),
                ('veterinario', models.CharField(blank=True, max_length=200)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saude_registros', to='produtor_dashboard.animal')),
            ],
            options={
                'verbose_name': 'Registro de Saúde',
                'verbose_name_plural': 'Registros de Saúde',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('area_total_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area_util_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('endereco', models.TextField(blank=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fazendas/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fazenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cadastro', 'Cadastro'), ('saude', 'Saúde'), ('financeiro', 'Financeiro'), ('alimentacao', 'Alimentação'), ('venda', 'Venda')], max_length=20)),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='produtor_dashboard.fazenda'),
        ),
        migrations.CreateModel(
            name='AlimentacaoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo_racao', models.CharField(max_length=100)),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacao_registros', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Registro de Alimentação',
                'verbose_name_plural': 'Registros de Alimentação',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('saude', 'Saúde'), ('alimentacao', 'Alimentação'), ('reproducao', 'Reprodução'), ('financeiro', 'Financeiro'), ('sistema', 'Sistema')], max_length=20)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_animais', models.IntegerField(default=0)),
                ('nascimentos', models.IntegerField(default=0)),
                ('mortes', models.IntegerField(default=0)),
                ('vendas', models.IntegerField(default=0)),
                ('peso_medio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('taxa_mortalidade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('natalidade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dados_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Relatório de Produção',
                'verbose_name_plural': 'Relatórios de Produção',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('categoria', models.CharField(choices=[('venda_animal', 'Venda de Animal'), ('venda_produto', 'Venda de Produto'), ('racao', 'Ração'), ('veterinario', 'Veterinário'), ('medicamentos', 'Medicamentos'), ('equipamentos', 'Equipamentos'), ('manutencao', 'Manutenção'), ('funcionarios', 'Funcionários'), ('outros', 'Outros')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='produtor_dashboard.animal')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueAlimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_racao', models.CharField(max_length=100)),
                ('quantidade_atual_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_minima_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('custo_por_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_alimentacao', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Estoque de Alimentação',
                'verbose_name_plural': 'Estoques de Alimentação',
                'unique_together': {('fazenda', 'tipo_racao')},
            },
        ),
    ]
