# Generated by Django 6.0.1 on 2026-05-30 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentacaoregistro',
            name='quantidade_sacos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade de sacos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimentacaoregistro',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alimentacaoregistro',
            name='quantidade_kg',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('bovino', 'Bovino')], max_length=20),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('saude', 'Saúde'), ('financeiro', 'Financeiro'), ('alimentacao', 'Alimentação'), ('venda', 'Venda'), ('compra', 'Compra')], max_length=20),
        ),
        migrations.CreateModel(
            name='TipoRacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso_por_saco', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Peso por saco (kg)')),
                ('preco_por_saco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço por saco (AOA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_racao', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Tipo de Ração',
                'verbose_name_plural': 'Tipos de Ração',
                'unique_together': {('fazenda', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='EstoqueRacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sacos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade de sacos')),
                ('estoque_minimo_sacos', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Estoque mínimo (sacos)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_racao', to='produtor_dashboard.fazenda')),
                ('tipo_racao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='produtor_dashboard.tiporacao')),
            ],
            options={
                'verbose_name': 'Estoque de Ração',
                'verbose_name_plural': 'Estoques de Ração',
                'unique_together': {('fazenda', 'tipo_racao')},
            },
        ),
        migrations.CreateModel(
            name='CompraRacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade_sacos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade de sacos')),
                ('quantidade_kg', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota_fiscal', models.CharField(blank=True, max_length=100)),
                ('fornecedor', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_racao', to='produtor_dashboard.fazenda')),
                ('tipo_racao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='produtor_dashboard.tiporacao')),
            ],
            options={
                'verbose_name': 'Compra de Ração',
                'verbose_name_plural': 'Compras de Ração',
                'ordering': ['-data'],
            },
        ),
        migrations.AlterField(
            model_name='alimentacaoregistro',
            name='tipo_racao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes', to='produtor_dashboard.tiporacao'),
        ),
        migrations.DeleteModel(
            name='EstoqueAlimentacao',
        ),
    ]
