# Generated by Django 6.0.1 on 2026-06-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor_dashboard', '0002_alimentacaoregistro_quantidade_sacos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasNotificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertas_saude', models.BooleanField(default=True)),
                ('alertas_estoque', models.BooleanField(default=True)),
                ('alertas_relatorios', models.BooleanField(default=False)),
                ('frequencia_saude', models.CharField(default='imediato', max_length=20)),
                ('frequencia_estoque', models.CharField(default='imediato', max_length=20)),
                ('frequencia_relatorios', models.CharField(default='mensal', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fazenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacoes', to='produtor_dashboard.fazenda')),
            ],
            options={
                'verbose_name': 'Preferência de Notificações',
                'verbose_name_plural': 'Preferências de Notificações',
            },
        ),
    ]
